# Generated by Django 5.0.7 on 2024-07-09 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppings', models.TextField()),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzerian_logs.pizza')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
